### ISSUE TITLE
Extra revisions with no changes

### ISSUE THREAD

**Issue by celynw** [lostintangent/gistpad#189]
**Describe the bug**
Saving a file with no changes still makes a commit with no changes.

**To Reproduce**
1. Have a gist note.
2. Add some text then remove it again
3. Save the note

**Expected behavior**
As there were no changes, don't commit and push another revision.

**Screenshots**
This is how it looks in GitHub proper.
![image](https://user-images.githubusercontent.com/3299161/99564242-17863e00-29c2-11eb-81a7-a099cfc22b42.png)

**Desktop (please complete the following information):**
 - VS Code Version: 1.51.1
 - GistPad Version 0.1.9

**Additional context**
Maybe the ability to disable this this is a feature request? Seems unlikely anybody would want this behaviour though.

**Comment by lostintangent** [comment]
Thanks for reporting this! I'm surprised to hear this could happen 🤔 VS Code tracks changes between saves, which should prevent the gist file from being in a "dirty" state after your repro steps.

I agree this behavior doesn't make sense. And so instead of adding a setting, I'll look and see how to prevent saving unchanged files 👍

**Comment by lostintangent** [comment]
I'm going close this as resolved since I think it's a behavior in VS Code that I can't control. And I haven't received any other reports of it causing an issue for users. That said, please let me know if this is still an issue and I can try to take a look at it again. Thanks!
