### ISSUE TITLE
Keyboard navigation of "file explorer" closer to that of VSCode standard Explorer

### ISSUE THREAD

**Issue by Sheraff** [lostintangent/gistpad#232]
In the "native" VSCode Explorer, there are a few keyboard shortcuts that I tend to find pretty useful:
- left: close folder (if focus is on folder and folder it open), otherwise focus parent folder
- right: if focus on folder, open folder (if folder is closed), or focus first child (if folder is open)
- enter: rename file / confirm current renaming
- space: open/close folder if focus is on folder, open file otherwise (focus remains on Explorer)

My issue is that these keyboard controls get messy when used in the GistPad explorer.
- space: if focus is on a file, the file opens *and the editor steals the focus*. It shouldn't steal the focus.
- enter: does the same as space. It should enter "renaming" mode.

In addition to those, a keyboard shortcut to open focused gist (what is right now the icon with tooltip "open gist") would be awesome, especially for CodeSwing gists. The most intuitive and least conflicting I can think of would be either
- when opening any file from a CodeSwing gist, if it isn't the active one
- enter on the "folder" (conflicts with renaming, but still seems intuitive, and we probably rename less often than we open)

**Comment by lostintangent** [comment]
Unfortunately, the native file explorer is able to achieve special behavior, that custom trees can't. GistPad tries to emulate the file explorer's behavior as much as possible, but I can't actually implement rename-on-space using the current editor support*

Furthermore, I _think_ I could prevent `ENTER` from stealing focus, but that would impact the behavior of mouse-clicking the file as well, since VS Code doesn't let extensions distinguish between these two actions. I'll take a look again and see what's possible.

* Technically I could, but it would require reimplementing the entire tree as a custom WebView, which isn't something I'd want to maintain.

**Comment by Sheraff** [comment]
> I think I could prevent ENTER from stealing focus, but that would impact the behavior of mouse-clicking the file as well

Actually with the native file explorer, a single click behaves the same as `SPACE` (opens the editor, leaves focus on explorer). It's the double click that takes the focus away.

> *Technically I could, but it would require reimplementing the entire tree as a custom WebView*

Yeah that does sound like a bad idea! 

Thanks for all the work, it's awesome!

**Comment by lostintangent** [comment]
As I thought, there's not really much I can do here. The current keyboard navigation behavior is the closest I can do to emulate the file explorer, without needing to reimplement the tree as a WebView. Due to that, I'm going to close this issue as won't fix for now, and we can reopen it if there's significant demand for changes here. Thanks!

**Comment by Sheraff** [comment]
@lostintangent alright, thanks for considering it! I feel like I should open a ticket on vscode but they have so much on their plate already!

**Comment by cdsaenz** [comment]
I wonder if there's a way to at least assign a keyboard shortcut to gistpad.changeGistDescription? I've got lots of changes to be done and I'd like to avoid the mouse. I tried to assign F2 (or even a rare unused combination of keystrokes) and it shows up in the context menu but it doesn't trigger the action. Maybe I need to indicate some condition in "when"? Thanks!
