### ISSUE TITLE
Unable to open: assertion failed. Argument is undefined or null.

### ISSUE THREAD

**Issue by ijyliu** [lostintangent/gistpad#239]
**Describe the bug**
When opening certain gists in markdown, I get the error unable to open: assertion failed. Argument is undefined or null.

**Screenshots**
![image](https://user-images.githubusercontent.com/67396209/129451459-45dffea8-0fee-43c9-9b2d-c64992f5e6ce.png)

**To Reproduce**
This only occurs for one particular file I have. Notes about that file:
1. It is long, 800-ish lines
2. It is in markdown
3. It is a secret gist
4. Don't know if this is related, but when I try to open it the icon in the screenshot appears rather than this one, which is what I normally see for secret gists: 
![image](https://user-images.githubusercontent.com/67396209/129451584-4b98034f-29da-47ba-8694-180dd6787911.png)
5. File name originally contained spaces and dashes, but I went on GitHub.com and replaced the spaces with _ and it's still not opening.

**Expected behavior**
File should open for editing.

**Desktop (please complete the following information):**
 - VS Code Version 1.59
 - GistPad Version v0.3.0

**Comment by lostintangent** [comment]
Thanks for reporting this! I haven't seen this bug before, so I'd love to help track it down. The fact that it's a secret gist, and a markdown file, shouldn't be a problem. And I don't believe the file name is an issue either, though I'll try to repro this and confirm.

Maybe it's related to it being a large file? I'll have to check. Would you be comfortable sharing the gist URL with me? Maybe over email (joncart@microsoft.com)? That would simply let me try to debug this exact case. Otherwise, I'll try to recreate a 800-line file and see if I can repro it. Stay tuned!

**Comment by ijyliu** [comment]
Yeah, I think file length's the issue

I can't open the following:

https://gist.github.com/ijyliu/f97f1d5eaf201e18930c3270d2faa3db

**Comment by lostintangent** [comment]
Alright awesome, thanks for helping confirm that. I'll investigate this issue this afternoon and see what might be going on. I'm hoping there isn't a bug in the Gist API 😃

**Comment by lostintangent** [comment]
Ugh, I'm unable to repro this issue. Including when using the sample gist you shared. I also tried a bunch of other large files, and never hit this problem.

I'm using the same version of VS Code and GistPad as you, and so I'm curious what the other variables might be. Let me keep looking and see where in the code path, this issue might occur.

**Comment by lostintangent** [comment]
I still haven't been able to repro this unfortunately, so I'm going to close it as resolved. If you're still able to repro it, please let me know, since I definitely want to narrow it down and fix any bugs. Thanks!
