### ISSUE TITLE
support for other gist providers? (gitlab snippets, bitbucket snippets, etc)

### ISSUE THREAD

**Issue by christian-korneck** [lostintangent/gistpad#242]
Thanks a lot for this great vscode extension. As many git repo managers (like GitLab or Bitbucket) have an equivalent feature to GitHub Gists, would it maybe make sense to add support for multiple providers?

I know this is a big topic and this issue is just meant to start a discussion. Would it be feasible at all (or is i.e. the feature gap between these providers too large)? Is it within the scope of this project (or would it make more sense to create a dedicated vscode extension for every provider)? etc ...

**Comment by lostintangent** [comment]
I'd love to do this, but realistically, I wouldn't have the time to support any other providers. It would also require a huge refactoring of the codebase, and so I think it would actually be simpler to just create a different extension for GitLab or BitBucket. Because of that, I'm going to close this for now, and we can reconsider, if the demand is significant enough. Thanks!
