### ISSUE TITLE
An option to create secret gist by default insetad of public

### ISSUE THREAD

**Issue by erkage** [lostintangent/gistpad#254]
A new option for the default type of the gist which change all the plus icons (new gist) behavior of creating a public or secret gist.

**Comment by ameeno** [comment]
any updates? would love a flag to swap default to secret and make it public if want to.

**Comment by lostintangent** [comment]
The button to the right of the plus icon, is actually the button for creating a secret gist. So there's not necessarily a "default" gist type, there's just two distinct buttons for public and secret.

That said, I agree that using a generic plus icon for public gists, kind of gives the impression that it's the default. So instead of creating a setting, I can maybe just make the plus icon create secret gists, and then use a distinct icon for creating public gists. Thoughts?

**Comment by mfsbo** [comment]
A +icon with a lock on it is better than a document icon with a lock on it next to a + icon.

**Comment by chunhualiao** [comment]
I need one option to set the button to public.

**Comment by lostintangent** [comment]
I just changed the `+` icon to create a secret gist, so that you get a secret gist "by default".
