### ISSUE TITLE
Add settings to configure default file location

### ISSUE THREAD

**Issue by douglance** [lostintangent/gistpad#308]
**Is your feature request related to a problem? Please describe.**

I have a repo full of markdown files that I want to sync to a shared file server(iCloud, Dropbox, Google Drive, etc.) as well as Git. 

**Describe the solution you'd like**

An additional extension setting to be able to select where to keep the files synced by Gistpad on my local machine. 

**Describe alternatives you've considered**

I've tried a bunch of other ways to sync my notes to all of my devices, and this is the simplest option.

**Additional context**

It'd be nice to be able to set the location based on project/gist but I understand the complexity of that request with the current UI might be tricky.

**Comment by lostintangent** [comment]
Hey! At the moment, syncing between local files and gists is outside the scope of this extension. It's a pretty tricky capability to get right, and since I don't have a ton of capacity for maintaining this extension, I'll unfortunately need to prioritize features/bugs that fit into the current scope (I.e. remotely editing gists). 

So I'm going to close this as "not planned", but I appreciate the feedback 🙏
