### ISSUE TITLE
synchronization of the gist file with the local file that we have copied file to gist...

### ISSUE THREAD

**Issue by runtimevic** [lostintangent/gistpad#339]
Hello, 
I have copied file to gist and then we modify the local file and it does not synchronize with the file on github...
because the local file is not synchronized with the file on Github with gistpad?

**Comment by lostintangent** [comment]
Hey! Since GistPad is focused on editing gists/repos, and enabling users to share files as gists, I think that syncing local files with gist is outside of the scope of this extension. I agree that it would be compelling, but I haven't heard much feedback for it, and I wouldn't use it in my own workflow. So I don't think I'll be able to prioritize maintaining that behavior, unless someone wanted to submit a PR 👍

**Comment by runtimevic** [comment]
What do you use to sync local files with gist on github then in your workflow?

**Comment by lostintangent** [comment]
I built GistPad so that I could create and edit files entirely in the cloud, via gist or GitHub repos. So I don't use anything to sync, since I never actually have files locally in the first place. But that's just my workflow, since I also use Codespaces for development, Google docs, etc. an so I don't store any state on my local machine at all.
